FROM python:3.8-buster

COPY . backend/
WORKDIR /backend

RUN pip install --upgrade pip
RUN pip install tqdm
RUN pip install click
RUN pip install flask
RUN pip install pyyaml
RUN pip install pandas
RUN pip install gensim
RUN pip install sklearn
RUN pip install inflect
RUN pip install requests
RUN pip install graphviz
RUN pip install networkx
RUN pip install beautifulsoup4
RUN pip install transformers==4.10.3
RUN pip install sentence_transformers















